### ISSUE TITLE
Looks like you're requiring pry, but don't have it listed as a dependency.

### ISSUE THREAD

**Issue by webdestroya** [Altivi/lz_string#1]
https://github.com/Altivi/lz_string/blob/220f64f53953e02e2fbb75c4e03ee82813c11dcc/lib/lz_string.rb#L1

```Traceback (most recent call last):
	3: from decode.rb:1:in `<main>'
	2: from decode.rb:1:in `require'
	1: from /Users/something/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/lz_string-0.1.1/lib/lz_string.rb:1:in `<top (required)>'
/Users/something/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/lz_string-0.1.1/lib/lz_string.rb:1:in `require': cannot load such file -- pry (LoadError)```

**Comment by altivi** [comment]
Thanks @webdestroya, dependencies updated.
